version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.1.0-20211123
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    ports:
      - "7900:7900"

  edge:
    image: selenium/node-edge:4.1.0-20211123
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7901:7900"

  firefox:
    image: selenium/node-firefox:4.1.0-20211123
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7902:7900"

  selenium-hub:
    image: selenium/hub:4.1.0-20211123
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  juice-shop:
    image:  bkimminich/juice-shop
    ports:
      - "3000:3000"